### ISSUE TITLE
Is there an easy way to rotate an image using the visual editor?

### ISSUE THREAD

**Issue by Sslaxx** [ben-rolfe/icbm#1]
As per the subject title, really. Adding an image gives the options to resize and move the image, but not to rotate it.

**Comment by ben-rolfe** [comment]
Currently, there's not, but it's planned, and since you've mentioned it, I'll prioritise it. (Images are actually a recent addition - the original plan was for the background to be the only image, but I realised that that was too restrictive.) My plan is to have scale (both axes at once, as already implemented), rotate, flip H and flip V, but no more complex manipulations than that. I'll also be adding a multiplicative tint colour that might be useful both for adjusting colour and transparency.

I'll leave this issue open until I've implemented those features.

**Comment by ben-rolfe** [comment]
Images can now be rotated and flipped (horizontally - if required, a vertical flip can be achieved with a 180 degree rotation and horizontal flip)
